version: "3"
services:
  sbolexplorer:
    image: michael13162/sbolexplorer:latest
    ports:
      - "13162:13162"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - "9200:9200"
