sudo: required

services:
    - docker

script:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      cd flask/docker;
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker build -t michael13162/synbiohub:snapshot -f docker/Dockerfile .;
      docker build -t michael13162/synbiohub:snapshot-synbiohub -f docker/Dockerfile-synbiohub.;
      docker push michael13162/synbiohub:snapshot;
      docker push michael13162/synbiohub:snapshot-synbiohub;
      fi
