name: Run release 

on: push

jobs:

  build-docker:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
          docker build . --file flask/docker/Dockerfile --tag myersresearchgroup/sbolexplorer:snapshot
          docker build . --file flask/docker/Dockerfile-synbiohub --tag myersresearchgroup/sbolexplorer:snapshot-synbiohub
    - uses: azure/docker-login@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the image to Docker Hub
      run: |
          docker push myersresearchgroup/sbolexplorer:snapshot
          docker push myersresearchgroup/sbolexplorer:snapshot-synbiohub
